# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25, unique=True)),
                ('elemento', models.CharField(max_length=25, unique=True)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('descripcion', models.CharField(max_length=45)),
                ('valorCompra', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('valorIva', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('valorVenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
