# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20170825_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=25, unique=True, verbose_name='C\xf3digo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(max_length=45, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='valorCompra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor de compra'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='valorIva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='valorVenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor de venta'),
        ),
    ]
