# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=15, unique=True)),
                ('nombreEmpresa', models.CharField(max_length=45)),
                ('nombreRepresentante', models.CharField(max_length=45)),
                ('apellidoRepresentante', models.CharField(max_length=45)),
                ('telefonoUno', phonenumber_field.modelfields.PhoneNumberField(default='+570387260001', max_length=128)),
                ('telefonoDos', phonenumber_field.modelfields.PhoneNumberField(default='+573040000001', max_length=128)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('sitioWeb', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=45)),
                ('banco', models.CharField(max_length=45)),
                ('tipoCuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros')], max_length=25)),
                ('numeroCuenta', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
