# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_auto_20170621_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='apellidoRepresentante',
            field=models.CharField(max_length=45, verbose_name='Apellido de representante'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombreEmpresa',
            field=models.CharField(max_length=45, verbose_name='Nombre de empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombreRepresentante',
            field=models.CharField(max_length=45, verbose_name='Nombre de representante'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numeroCuenta',
            field=models.CharField(max_length=15, unique=True, verbose_name='N\xfamero de cuenta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sitioWeb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefonoDos',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+573040000001', max_length=128, verbose_name='Tel\xe9fono 2'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefonoUno',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+570387260001', max_length=128, verbose_name='Tel\xe9fono 1'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipoCuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros'), ('recaudo', 'Recaudo')], max_length=25, verbose_name='Tipo de cuenta'),
        ),
    ]
