# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='+570387260001', max_length=128)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('tipoCuenta', models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros'), ('recaudo', 'Recaudo')], max_length=25, null=True)),
                ('numeroCuenta', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
