# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
