# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170705_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='N\xfamero de identificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numeroCuenta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N\xfamero de cuenta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoCuenta',
            field=models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros'), ('recaudo', 'Recaudo')], max_length=25, null=True, verbose_name='Tipo de cuenta'),
        ),
    ]
