# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(max_length=45, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numeroDocumento',
            field=models.CharField(max_length=15, unique=True, verbose_name='N\xfamero de Documento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+573040000000', max_length=128, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
