# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_auto_20170621_2020'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0002_auto_20170705_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('valorIva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('serie', models.IntegerField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('formaPago', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta debito', 'Tarjeta debito'), ('tarjeta credito', 'Tarjeta credito'), ('venta a credito', 'Venta a credito'), ('bono', 'Bono'), ('vale', 'Vale'), ('otros', 'Otros')], max_length=50, verbose_name='forma de pago')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.Factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Inventario'),
        ),
    ]
