# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20170814_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(max_length=45, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='valorIva',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor IVA'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta d\xe9bito', 'Tarjeta d\xe9bito'), ('tarjeta cr\xe9dito', 'Tarjeta cr\xe9dito'), ('venta a cr\xe9dito', 'Venta a cr\xe9dito'), ('bono', 'Bono'), ('vale', 'Vale'), ('otros', 'Otros')], max_length=50, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='maquina',
            field=models.CharField(max_length=20, verbose_name='M\xe1quina'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
